# COMMENTS:
# (CTRL/) TURNS ANY LINE OF CODE INTO A COMMENT OR CONVERTS A LINE TO BE USED AS A COMMENT. IT CAN ALSO TURN A LINE BACK INTO A CODE. TO ADD A COMMENT ON A LINE OF CODE WITHOUT TURNING THE CODE INTO A COMMENT USE (SHIFT #) AFTER THE CODE.

# PRINT STATEMENT: PRINT STATEMENTS IS A FUNCTION USED TO DISPLAY OUTPUT OF THE PROGRAM TO THE USER.
print("hello will")

# CREATE A VARIABLE: A VARIABLE IS ALWAYS LOWER CASE AND USES _ FOR SPACES, IT ALSO CAN NOT CONTAIN ANY SYMBOLS OR LEADING NUMBERS. A VARIABLE MUST BE ASSIGNED (=) A VALUE (something).
last_name = "rosa"
age = 32
price = 10.77  # THE PRICE OF A CHEESE PIZZA AND A LARGE SODA

# INPUT: IS A FUNCTION THAT THE PROGRAM USES TO INTERACT WITH THE USER OF SAID PROGRAM. A PROGRAM ALWAYS READS (INPUT) DATA AS A (STRING).
name = input(
    "What is your name? "
)  # "WHAT IS YOUR NAME" IS ASKED TO THE USER AND THE USER CAN INPUT DATA TO ANSWER THE PROGRAM.

# (\n): THIS IS A FUNCTION THAT CREATES A LINE SPACE LIKE HITTING ENTER IN WORD DOC.
print("hello\nwill")

# (\t): THIS IS A FUNCTION THAT CREATES A TAB SPACE LIKE HITTING TAB IN WORD DOC.
print("hello\twill")

# (\"): THIS IS A FUNCTION THAT LETS YOU INSERT " MARKS INTO A STRING.
print('"hello will"')  # this will print as ("hello will") instead of (hello will).

# STRING: A STRING IS A DATA TYPE THAT IS A SET OF CHARACTERS IN A LINE OF CODE SURROUNDED BY "" - "hdifgbso" "746293" 'hfosuduifn' '09348675'. # FYI: "" IS THE SAME AS A INPUT OF NOTHING.

# (INT): IS A DATA TYPE THAT HANDLES WHOLE NUMBERS ONLY (INTEGERS). # (int) IS A FUNCTION IN CODING.
integer = 3

# (FLOAT): IS A DATA TYPE THAT HANDLES DECIMALS ONLY.
float_ = 0.5  # NOTICE I PUT A SPACE OR _ IN THE VARIABLE (float_) BECAUSE (float) IS A FUNCTION IN CODING.

# (TRUE/FALSE): IS A DATA TYPE KNOWN AS A BOOL OR BOOLEAN, IT REPRESENTS 1 OF 2 VALUES, AND SERVES AS A FOUNDATION FOR DECISION BASED PROGRAMS. THE FIRST LETTER OF EITHER TRUE OR FALSE MUST BE CAPITALIZED THE REST LOWER CASE.
will_is_hungry = True

# MATH OPERATORS: + ADDITION, - SUBTRACTION, * MULTIPLICATION, / DIVISION (ALWAYS EQUALS A FLOAT), // FLOOR DIVISION (CHOPS OFF DECIMALS), % MODULUS (GIVE THE REMAINDER ONLY), ** EXPONENT/POWER. IF YOU TRY TO DO MATH WITH (STRINGS) THE PROGRAM WILL THROW AN ERROR OR COMBINED THE (INPUTS) TOGETHER. "SIDE" + "SIDE" THE PROGRAM WILL OUTPUT "SIDESIDE".THIS IS CALLED CONCATENATION.

# CONVERTING STRINGS TO (int), (float) TO PERFORM CALCULATIONS: IN ORDER TO DO MATH/CALCULATIONS IN PROGRAMMING WE MUST CONVERT USER INPUT DATA TO INTEGERS OR DECIMALS.
cost = float(
    input("How much is this? ")
)  # THIS TAKES THE USER INPUT SAY 10.77 AND CONVERTS IT TO A FLOAT THAT WAY WE CAN DO MATH/CALCULATIONS WITH IT.
ticket = int(
    input("How Many tickets do you need? ")
)  # THIS TAKES THE USER INPUT SAY 6 AND CONVERTS IT TO A INTEGER THAT WAY WE CAN DO MATH/CALCULATIONS WITH IT.

# FORMATTED STRINGS OR (f-strings): F-STRINGS ARE A WAY TO EMBED OR INSERT VARIABLES/EXPRESSIONS INTO A NORMAL STRING USING {} CURLY BRACES. YOU CAN INPUT MOVEMENT/SPACING FOR (f-string) VARIABLES/EXPRESSIONS WITH :>23, :<23, {___:>23}
print(f"{name} is {age} years old.")

# YOU CAN PUT AN (f-string) INSIDE OF ANOTHER (f-string) FOR CERTAIN WANTED OUTPUTS.
# FORMATTING NUMBERS: (:.2f) THIS IS USED IN (f-strings) TO SHOW DECIMALS THE 2 MEANS IT WILL ONLY SHOW TWO DECIMAL PLACES. (:,.2f): THIS DOES THE SAME AS THE FIRST WITH THE ADDITION OF SHOWING A THOUSAND COMMA PLACE.
print(f"Your order is {f'${cost:.2f}':>21}")
print(f"Your order is {f'${cost:,.2f}':>21}")

# FORMATTING PERCENTAGES: THE (:.1%) FUNCTION HANDLES PERCENTAGES BY DOING THE MATH FOR YOU. THE (.1) MEANS THAT THE OUTPUT WILL SHOW ONE DECIMAL PLACE OF THE PERCENTAGE.
score = 0.857
print(f"You received a {score:.1%} on the test.")

# COMPARISON OPERATORS: THESE ARE USED TO COMPARE INPUTS, VARIABLES, AND OTHER FORMS OF DATA.
# (==) EQUALS TO, (!=) NOT EQUAL TO, (>) GREATER THAN, (<) LESS THAN, (>=) GREATER THAN OR EQUAL TO, (<=) LESS THAN OR EQUAL TO.
# IF/ELIF/ELSE OPERATORS: THESE CHECK IF A CONDITION IS TRUE OR FALSE. (if) THE CONDITION IS TRUE THE FOLLOWING CODE RUNS, IF THE CONDITION IS FALSE THE CODE SKIPS THE CODE AND GOES TO THE NEXT CONDITION CHECK USUALLY (elif). (elif) IS SHORT FOR ELSE/IF MEANING AFTER (if) IF ELSE CONDITION IS CHECKED (elif). YOU CAN HAVE MANY (elif)s WITH MANY DIFFERENT CONDITION CHECKS. AFTER (elif) THERE IS NOTHING LEFT BUT (else) THIS IS THE LAST OF THE CONDITION CHECKS, USUALLY THERE IS A LIST SOMETIMES THERE IS NOT. IF ALL (if)/(elif)s TURN OUT TO BE FALSE THEN THE REST IS (else) and its code runs.
will_age = 21
if will_age == 21:
    print("Will can drink")
elif will_age != 21:
    print("Will can not drink")
elif will_age > 21:
    print("Will can drink")
elif will_age < 21:
    print("Will can not drink")
elif will_age >= 21:
    print("Will can drink")
elif will_age <= 21:
    print("Will can not drink unless he is 21")

# PATTERN MATCHING: (match:case) IS FOR COMPARING/MATCHING VARIABLES VALUES TO CERTAIN "CASES". USUALLY A USERS INPUT TO A CERTAIN OUTPUT. (match) something to a (case) for the correct output. (case _:) acts like (else) it catches whatever the user inputs that it can not match and outputs accordingly. USE MATCH:CASE WHEN: YOU ARE COMPARING A SINGLE VARIABLE OR EXPRESSION AGAINST A SERIES OF DISCRETE, EXACT VALUES OR DATA PATTERNS SUCH AS MENU CHOICES, COMMAND STRINGS, STATUS CODES, OR STRUCTURAL DATA TYPEES. IT KEEPS MULTI-WAY DISCRETE VALUE CHECKS CLEANER AND MORE READABLE. USE (if/elif/else) WHEN: YOUR CONDITIONS INVOLVE RANGES OF VALUES LIKE NUMERIC THRESHOLDS, AGE < 16, INDEPENDENT BOOLEAN EXPRESSIONS, OR MULTIPLE DIFFERENT VARIABLES EVALUATED TOGETHER IN COMPLEX LOGICAL COMPARISONS.
user_month = input("What month is it? ")
match user_month:
    case "january":
        print("New year!")
    case "february":
        print("Valentine's Day!")
    case "march":
        print("Spring!")
    case _:
        print("Try january, february, or march.")

# (.upper()): IS A FUNCTION THAT USUALLY GOES ON THE END OF CODE THAT IS USED TO MAKE ALL ABC CHARACTERS CAPITALIZED.

# (.lower()): DOES THE OPPOSITE OF (.upper()).

# (and/or/not):
